version: "3"

services:
  luigid:
    image: luigid:v1
    container_name: luigid
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    command: "luigid --port 8082"
    volumes:
      - luigi_db:/usr/local/var

volumes:
  luigi_db:
